/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type ChatsMessageSource = "telegram" | "web";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Language = "de" | "en";

export type Numeric = ColumnType<string, number | string, number | string>;

export type ProviderModelCapabilities = "embedding" | "text" | "tts";

export type ProviderProviderType = "anthropic" | "google" | "openai" | "openai-compatible" | "openrouter";

export type Role = "assistant" | "user";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ChatsConversations {
  archived: Generated<boolean>;
  chatModelId: Int8;
  createdAt: Generated<Timestamp>;
  ephemeral: Generated<boolean>;
  id: Generated<Int8>;
  personaId: Int8 | null;
  personaModifierId: Int8 | null;
  rollingSummary: string | null;
  rollingSummaryCreatedAt: Generated<Timestamp>;
  rollingSummaryEnabled: Generated<boolean>;
  rollingSummaryModelId: Int8 | null;
  title: string;
  updatedAt: Generated<Timestamp>;
  userProfileId: Int8 | null;
}

export interface ChatsMessages {
  attachments: Json | null;
  content: string;
  conversationId: Int8;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  inputTokens: Generated<number>;
  outputTokens: Generated<number>;
  role: Role;
  source: ChatsMessageSource;
  toolCalls: Json | null;
  totalTokens: Generated<number | null>;
  updatedAt: Generated<Timestamp>;
  voiceInfo: Json | null;
}

export interface PersonasModifiers {
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  personaId: Int8;
  systemPromptModifier: string;
  updatedAt: Generated<Timestamp>;
}

export interface PersonasPersonas {
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  language: Generated<Language>;
  name: string;
  systemPrompt: string;
  updatedAt: Generated<Timestamp>;
}

export interface PersonasUserProfiles {
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  language: Generated<Language>;
  name: string;
  profile: string;
  updatedAt: Generated<Timestamp>;
}

export interface ProviderModels {
  capabilities: Generated<ArrayType<ProviderModelCapabilities>>;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  /**
   * Price per million input tokens
   */
  inTokensPrice: Numeric | null;
  name: string;
  /**
   * Price per million out tokens
   */
  outTokensPrice: Numeric | null;
  providerId: Int8;
  updatedAt: Generated<Timestamp>;
}

export interface ProviderProviders {
  createdAt: Generated<Timestamp>;
  endpoint: string | null;
  id: Generated<Int8>;
  name: string;
  type: Generated<ProviderProviderType>;
  updatedAt: Generated<Timestamp>;
}

export interface SystemSettings {
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  updatedAt: Generated<Timestamp>;
  value: Generated<Json | null>;
}

export interface DB {
  "chats.conversations": ChatsConversations;
  "chats.messages": ChatsMessages;
  "personas.modifiers": PersonasModifiers;
  "personas.personas": PersonasPersonas;
  "personas.userProfiles": PersonasUserProfiles;
  "provider.models": ProviderModels;
  "provider.providers": ProviderProviders;
  "system.settings": SystemSettings;
}
