/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type ChatsMessageSource = "telegram" | "web";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Language = "de" | "en";

export type Numeric = ColumnType<string, number | string, number | string>;

export type ProviderModelCapabilities = "citation" | "embedding" | "stt" | "text" | "thinking" | "tools" | "tts" | "vision";

export type ProviderProviderType = "anthropic" | "google" | "mistral" | "openai" | "openai-compatible" | "openrouter";

export type Role = "assistant" | "user";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ChatsConversations {
  /**
   * Soft archive flag for hiding old conversations
   */
  archived: Generated<boolean>;
  /**
   * LLM model used for chat responses
   */
  chatModelId: Int8;
  createdAt: Generated<Timestamp>;
  /**
   * Ephemeral conversations are not loaded to memory
   */
  ephemeral: Generated<boolean>;
  id: Generated<Int8>;
  /**
   * Active persona for system prompt
   */
  personaId: Int8 | null;
  /**
   * Optional modifier applied to persona system prompt
   */
  personaModifierId: Int8 | null;
  /**
   * Auto-generated summary of conversation history
   */
  rollingSummary: string | null;
  /**
   * Timestamp of last rolling summary generation
   */
  rollingSummaryCreatedAt: Generated<Timestamp>;
  /**
   * Whether automatic rolling summaries are active
   */
  rollingSummaryEnabled: Generated<boolean>;
  /**
   * Model used for generating rolling summaries
   */
  rollingSummaryModelId: Int8 | null;
  title: string;
  updatedAt: Generated<Timestamp>;
  /**
   * User profile providing context to the LLM
   */
  userProfileId: Int8 | null;
}

export interface ChatsMessages {
  /**
   * File attachments (images, etc.)
   */
  attachments: Json | null;
  content: string;
  conversationId: Int8;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  inputTokens: Generated<number>;
  outputTokens: Generated<number>;
  role: Role;
  source: ChatsMessageSource;
  /**
   * JSON array of tool calls made by the assistant
   */
  toolCalls: Json | null;
  /**
   * Generated column: input_tokens + output_tokens
   */
  totalTokens: Generated<number | null>;
  updatedAt: Generated<Timestamp>;
  /**
   * Metadata for voice/TTS messages
   */
  voiceInfo: Json | null;
}

export interface PersonasModifiers {
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  personaId: Int8;
  systemPromptModifier: string;
  updatedAt: Generated<Timestamp>;
}

export interface PersonasPersonas {
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  language: Generated<Language>;
  name: string;
  systemPrompt: string;
  updatedAt: Generated<Timestamp>;
}

export interface PersonasUserProfiles {
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  language: Generated<Language>;
  name: string;
  profile: string;
  updatedAt: Generated<Timestamp>;
}

export interface ProviderModels {
  capabilities: Generated<ArrayType<ProviderModelCapabilities>>;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  /**
   * Price per million input tokens
   */
  inTokensPrice: Numeric | null;
  name: string;
  /**
   * Price per million out tokens
   */
  outTokensPrice: Numeric | null;
  providerId: Int8;
  updatedAt: Generated<Timestamp>;
}

export interface ProviderProviders {
  createdAt: Generated<Timestamp>;
  endpoint: string | null;
  id: Generated<Int8>;
  name: string;
  type: Generated<ProviderProviderType>;
  updatedAt: Generated<Timestamp>;
}

export interface SystemSettings {
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  updatedAt: Generated<Timestamp>;
  value: Generated<Json | null>;
}

export interface SystemUsageTracking {
  createdAt: Generated<Timestamp>;
  functionName: string;
  id: Generated<Int8>;
  inTokens: Generated<number>;
  modelId: Int8;
  outTokens: Generated<number>;
  source: ChatsMessageSource;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  "chats.conversations": ChatsConversations;
  "chats.messages": ChatsMessages;
  "personas.modifiers": PersonasModifiers;
  "personas.personas": PersonasPersonas;
  "personas.userProfiles": PersonasUserProfiles;
  "provider.models": ProviderModels;
  "provider.providers": ProviderProviders;
  "system.settings": SystemSettings;
  "system.usageTracking": SystemUsageTracking;
}
