services:
  postgres:
    image: pgvector/pgvector:pg18
    env_file: ../.env
    ports:
      - '5433:5432'
    volumes:
      - ../.local/pgdata:/var/lib/postgresql
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
